path_follower:
  ros__parameters:
    lookahead_distance: 1.0
    max_linear_velocity: 0.10
    max_angular_velocity: 0.4
    goal_tolerance: 0.3

obstacle_stop:
  ros__parameters:
    stop_distance: 5.0
    roi_width_ratio: 0.35
    roi_height_ratio: 0.35